// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show
        defaultTargetPlatform,
        kIsWeb,
        TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions
  web = FirebaseOptions(
    apiKey:
        'AIzaSyC_W9f_XswQU8ED8OKZtOrlDZB_PIcFy3Q',
    appId:
        '1:37335661908:web:976a27129e66e4c24fdcc1',
    messagingSenderId: '37335661908',
    projectId: 'spotify-clone-e9bc6',
    authDomain:
        'spotify-clone-e9bc6.firebaseapp.com',
    storageBucket:
        'spotify-clone-e9bc6.firebasestorage.app',
    measurementId: 'G-WCJDQ448KT',
  );

  static const FirebaseOptions
  android = FirebaseOptions(
    apiKey:
        'AIzaSyCS0YR8QGTzKqnaEh2yxF0UMRgT6pUtSeA',
    appId:
        '1:37335661908:android:218f9faefb1039854fdcc1',
    messagingSenderId: '37335661908',
    projectId: 'spotify-clone-e9bc6',
    storageBucket:
        'spotify-clone-e9bc6.firebasestorage.app',
  );

  static const FirebaseOptions
  ios = FirebaseOptions(
    apiKey:
        'AIzaSyAMxAZFtq-HKSePN7J9hDVs5bcQsfwS9Ak',
    appId:
        '1:37335661908:ios:56bc62de57ebc6824fdcc1',
    messagingSenderId: '37335661908',
    projectId: 'spotify-clone-e9bc6',
    storageBucket:
        'spotify-clone-e9bc6.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions
  macos = FirebaseOptions(
    apiKey:
        'AIzaSyAMxAZFtq-HKSePN7J9hDVs5bcQsfwS9Ak',
    appId:
        '1:37335661908:ios:56bc62de57ebc6824fdcc1',
    messagingSenderId: '37335661908',
    projectId: 'spotify-clone-e9bc6',
    storageBucket:
        'spotify-clone-e9bc6.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions
  windows = FirebaseOptions(
    apiKey:
        'AIzaSyC_W9f_XswQU8ED8OKZtOrlDZB_PIcFy3Q',
    appId:
        '1:37335661908:web:dbd42df83c44db0c4fdcc1',
    messagingSenderId: '37335661908',
    projectId: 'spotify-clone-e9bc6',
    authDomain:
        'spotify-clone-e9bc6.firebaseapp.com',
    storageBucket:
        'spotify-clone-e9bc6.firebasestorage.app',
    measurementId: 'G-BJ39G4LSGJ',
  );
}
